### ISSUE TITLE
boblogistics update broke replicating-belts

### ISSUE THREAD

**Issue by TehFreek** [shanemadden/factorio-replicating-belts#1]
boblogistics 0.16.16 changed a few belt things and now I get this on startup:

`Failed to load mods: __replicating-belts__/data-updates.lua:2: ...ting-belts__/prototypes/entity/replicating-belts-bob.lua:38: attempt to index local 'entity' (a nil value)`

**Comment by shanemadden** [comment]
Updated for Bob's reorganized entity IDs in update 0.16.6.
